services:
  web:
    image: jungelr/diplomska
    container_name: webapp
    platform: "linux/arm64"
    ports:
      - 8443:8443
    volumes:
      - ${KEY_STORE_PATH}:/etc/ssl/certs/springboot.p12
      - /sys/devices/platform/soc/fe200000.gpio:/sys/devices/platform/soc/fe200000.gpip
      - /sys/class/gpio:/sys/class/gpio
    restart: always
    depends_on:
      - db
    environment:
      - server.ssl.key-store-password=${KEY_STORE_PASSWORD}
      - server.ssl.key-password=${KEY_STORE_PASSWORD}
      - server.ssl.key-store=/etc/ssl/certs/springboot.p12
      - SPRING_PROFILES_ACTIVE=prod
      - spring.datasource.username=${POSTGRES_USER}
      - spring.datasource.password=${POSTGRES_PASSWORD}
      - spring.datasource.url=jdbc:postgresql://db:5432/postgres?currentSchema=public
  db:
    image: postgres:16.3-alpine3.20
    container_name: db
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - /mnt/nvme/data:/var/lib/postgresql/data