services:
  web:
    build: .
    platform: "linux/arm"
    ports:
      - 8443:8443
    volumes:
      - ${KEY_STORE_PATH}:/etc/ssl/carts/springboot.p12
    environment:
      - server.ssl.key-store-password=${KEY_STORE_PASSWORD}
      - server.ssl.key-password=${KEY_STORE_PASSWORD}
      - SPRING_PROFILES_ACTIVE=prod
